kind: Pod
apiVersion: v1
metadata:
 name: myfirstpod
 namespace: devolpment
spec:
 containers:
 - name: container1
   image: naveed0004/spring-integration
   imagePullPolicy: IfNotPresent
   ports:
   - containerPort: 8081
